/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * saveFileNamesDialog.java
 *
 * Created on Aug 2, 2010, 9:22:36 AM
 */
/**
 * 
DOCUMENT ME!
 *
 * @author jonathanjekeli
 */
public class SaveFileNamesDialog extends javax.swing.JDialog {
  private boolean clickedOK = false;

/** Creates new form saveFileNamesDialog */
  public SaveFileNamesDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do
   * NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    buttonGroup1 = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jSeparator2 = new javax.swing.JSeparator();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    veDataTextField = new javax.swing.JTextField();
    layoutDataTextField = new javax.swing.JTextField();
    optionsDataTextField = new javax.swing.JTextField();
    cancelBtn = new javax.swing.JButton();
    nextBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16));
    jLabel1.setText("Save Files");

    jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
    jLabel2.setText("<html>Saving this graph requires three files.  Please enter what you\n<br>would like to name them, and then click next to select a</br>\n<br>location for these three files (extensions automatically added).</br></html>");

    jLabel3.setText("Vertex/Edge Data: ");

    jLabel4.setText("Layout Data: ");

    jLabel5.setText("Options Data: ");

    veDataTextField.setText("");

    layoutDataTextField.setText("");

    optionsDataTextField.setText("");

    cancelBtn.setText("Cancel");
    cancelBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          cancelBtnActionPerformed(evt);
        }
      });

    nextBtn.setText("Save");
    nextBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          nextBtnActionPerformed(evt);
        }
      });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                     .add(layout.createSequentialGroup()
                                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                             .add(org.jdesktop.layout.GroupLayout.LEADING,
                                                                   layout.createSequentialGroup()
                                                                          .addContainerGap()
                                                                          .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                                                      .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING,
                                                                                                                       false)
                                                                                                  .add(org.jdesktop.layout.GroupLayout.LEADING,
                                                                                                        jSeparator2)
                                                                                                  .add(org.jdesktop.layout.GroupLayout.LEADING,
                                                                                                        jLabel2,
                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                                                  .add(org.jdesktop.layout.GroupLayout.LEADING,
                                                                                                        jLabel1)
                                                                                                  .add(org.jdesktop.layout.GroupLayout.LEADING,
                                                                                                        jSeparator1,
                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                        364,
                                                                                                        Short.MAX_VALUE))
                                                                                      .add(layout.createSequentialGroup()
                                                                                                  .add(jLabel3)
                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                  .add(veDataTextField,
                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                        236,
                                                                                                        Short.MAX_VALUE))
                                                                                      .add(layout.createSequentialGroup()
                                                                                                  .add(jLabel4)
                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                  .add(layoutDataTextField,
                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                        236,
                                                                                                        Short.MAX_VALUE))
                                                                                      .add(layout.createSequentialGroup()
                                                                                                  .add(jLabel5)
                                                                                                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                                                  .add(optionsDataTextField,
                                                                                                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                                                        236,
                                                                                                        Short.MAX_VALUE))))
                                                             .add(org.jdesktop.layout.GroupLayout.LEADING,
                                                                   layout.createSequentialGroup()
                                                                          .add(91, 91, 91)
                                                                          .add(cancelBtn)
                                                                          .add(18, 18, 18)
                                                                          .add(nextBtn)))
                                                 .addContainerGap()));
    layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                   .add(layout.createSequentialGroup().addContainerGap().add(jLabel1)
                                               .add(10, 10, 10)
                                               .add(jSeparator1,
                                                     org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                     org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                     org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                               .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                               .add(jLabel2,
                                                     org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                     org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                     org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                               .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                               .add(jSeparator2,
                                                     org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                     org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                     org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                               .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                               .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                           .add(jLabel3)
                                                           .add(veDataTextField,
                                                                 org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                 org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                 org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                               .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                               .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                           .add(jLabel4)
                                                           .add(layoutDataTextField,
                                                                 org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                 org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                 org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                               .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                               .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                           .add(jLabel5)
                                                           .add(optionsDataTextField,
                                                                 org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                                                 org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                 org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                               .add(18, 18, 18)
                                               .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                                           .add(cancelBtn).add(nextBtn))
                                               .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                                                 Short.MAX_VALUE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_nextBtnActionPerformed
    clickedOK = true;
    super.hide();
  } //GEN-LAST:event_nextBtnActionPerformed

  private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cancelBtnActionPerformed
    clickedOK = false;
    super.hide();
  } //GEN-LAST:event_cancelBtnActionPerformed

  /**
   * 
  DOCUMENT ME!
   *
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          SaveFileNamesDialog dialog = new SaveFileNamesDialog(new javax.swing.JFrame(), true);
          dialog.addWindowListener(new java.awt.event.WindowAdapter() {
              public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
              }
            });
          dialog.setVisible(true);
        }
      });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton cancelBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JTextField layoutDataTextField;
  private javax.swing.JButton nextBtn;
  private javax.swing.JTextField optionsDataTextField;
  private javax.swing.JTextField veDataTextField;

  // End of variables declaration//GEN-END:variables
  /**
   * DOCUMENT ME!
   *
   * @return DOCUMENT ME!
   */
  public boolean isClickedOK() {
    return clickedOK;
  }

  /**
   * DOCUMENT ME!
   *
   * @param clickedOK DOCUMENT ME!
   */
  public void setClickedOK(boolean clickedOK) {
    this.clickedOK = clickedOK;
  }

  /**
   * DOCUMENT ME!
   *
   * @return DOCUMENT ME!
   */
  public javax.swing.JTextField getLayoutDataTextField() {
    return layoutDataTextField;
  }

  /**
   * DOCUMENT ME!
   *
   * @param layoutDataTextField DOCUMENT ME!
   */
  public void setLayoutDataTextField(javax.swing.JTextField layoutDataTextField) {
    this.layoutDataTextField = layoutDataTextField;
  }

  /**
   * DOCUMENT ME!
   *
   * @return DOCUMENT ME!
   */
  public javax.swing.JTextField getOptionsDataTextField() {
    return optionsDataTextField;
  }

  /**
   * DOCUMENT ME!
   *
   * @param optionsDataTextField DOCUMENT ME!
   */
  public void setOptionsDataTextField(javax.swing.JTextField optionsDataTextField) {
    this.optionsDataTextField = optionsDataTextField;
  }

  /**
   * DOCUMENT ME!
   *
   * @return DOCUMENT ME!
   */
  public javax.swing.JTextField getVeDataTextField() {
    return veDataTextField;
  }

  /**
   * DOCUMENT ME!
   *
   * @param veDataTextField DOCUMENT ME!
   */
  public void setVeDataTextField(javax.swing.JTextField veDataTextField) {
    this.veDataTextField = veDataTextField;
  }
}
