/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusPanel.java
 *
 * Created on Aug 3, 2010, 3:38:59 PM
 */
import java.text.DecimalFormat;

/**
 *
 * @author jonathanjekeli
 */
public class StatusPanel extends javax.swing.JPanel {

	private final static int TYPE = 0;
	private final static int NAME = 1;
	private final static int INCOMING = 2;
	private final static int OUTGOING = 3;
	private final static int WEIGHT = 4;
	private final static int DEGREECENTR = 5;
	private final static int BETWEENCENTR = 6;
	private final static int LETTERNUM = 7;

	DecimalFormat form = new DecimalFormat("0.000");
	
    /** Creates new form StatusPanel */
    public StatusPanel() {
        initComponents();
    }
    
    public void setStatusBar(Node n)
    {
    	data[0][TYPE] = "Node";
    	data[0][NAME] = n.getLabel();
    	data[0][INCOMING] = "";
    	data[0][OUTGOING] = "";
    	data[0][WEIGHT] = String.valueOf(n.getCount());
    	data[0][DEGREECENTR] = form.format(n.getDegreeCentrality());
    	data[0][BETWEENCENTR] = form.format(n.getBetweenCentrality());
    	statusTable.setModel(new javax.swing.table.DefaultTableModel(
           data, columnTitles));
    	data[0][LETTERNUM] = "";
    }
    
    public void setStatusBar(Edge e)
    {
    	data[0][TYPE] = "Edge";
    	data[0][NAME] = "";
    	data[0][INCOMING] = e.to.getLabel();
    	data[0][OUTGOING] = e.from.getLabel();
    	data[0][WEIGHT] = String.valueOf(e.count);
    	data[0][DEGREECENTR] = "";
    	data[0][BETWEENCENTR] = form.format(e.getBetweenCentr());
    	statusTable.setModel(new javax.swing.table.DefaultTableModel(
           data, columnTitles));
    	data[0][LETTERNUM] = e.letterNum;
    }
    
    public void clearStatusBar()
    {
    	for(int i = 0; i < 5; i++)
    	{
    		data[0][i] = null;
    	}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
                
        data = new String [][] {
                {null, null, null, null, null, null, null, null} };
        columnTitles = new String [] {
                "Type", "Name", "Incoming", "Outgoing", "Connections",
                "Degree Centrality", "Betweenness Centralty", "Letter #"};
        
        setBorder(javax.swing.BorderFactory.createTitledBorder("Currently Selected: "));

        statusTable.setModel(new javax.swing.table.DefaultTableModel(
           data, columnTitles
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class, java.lang.String.class};
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(statusTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable statusTable;
    private String[][] data;
    private String[] columnTitles;
    // End of variables declaration//GEN-END:variables

}
